env:
  global:
   - secure: "j2ixQgkICLw5x+s66tSXTtxN7VXINtdut1ixtVQvO3yW32OQXYAoZLPGGC/hPKWCbfBW8CNgJDn3Yz/b7DSszHtwAPKCJKRuG62rJUQCowpuRYSf1wPAeWAHpML4iKkuVgO1mmsqwbZklYzCE/CLqNSyPK6EiW8Bnq91WwIpYyI="
language: cpp
os: linux
dist: trusty
sudo: required
compiler: clang
before_script: mkdir build && cd build
script: /bin/true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-7-dev
      - libcppunit-dev
  coverity_scan:
    project:
      name: "PADrend/Geometry"
      description: "Build submitted via Travis CI"
    notification_email: benjamin@eikel.org
    build_command_prepend: "cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGEOMETRY_BUILD_TESTS=ON .."
    build_command:   "cmake --build ."
    branch_pattern: coverity_scan
