language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - valgrind
            - libcppunit-dev
      env: CXX=g++-4.9
      before_install:
        - cd /tmp
        - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz --output-document=cmake.tar.gz
        - mkdir cmake
        - tar xzf cmake.tar.gz --strip-components=1 --directory cmake
        - export PATH=/tmp/cmake/bin:$PATH
        - cd -
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - valgrind
            - libcppunit-dev
      env: CXX=g++-5
      before_install:
        - cd /tmp
        - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz --output-document=cmake.tar.gz
        - mkdir cmake
        - tar xzf cmake.tar.gz --strip-components=1 --directory cmake
        - export PATH=/tmp/cmake/bin:$PATH
        - cd -
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - valgrind
            - libcppunit-dev
      env: CXX=clang++-3.6
      before_install:
        - cd /tmp
        - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz --output-document=cmake.tar.gz
        - mkdir cmake
        - tar xzf cmake.tar.gz --strip-components=1 --directory cmake
        - export PATH=/tmp/cmake/bin:$PATH
        - cd -
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - valgrind
            - libcppunit-dev
      env: CXX=clang++-3.7
      before_install:
        - cd /tmp
        - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz --output-document=cmake.tar.gz
        - mkdir cmake
        - tar xzf cmake.tar.gz --strip-components=1 --directory cmake
        - export PATH=/tmp/cmake/bin:$PATH
        - cd -
    - os: osx
      osx_image: xcode7.3
      compiler: gcc
      env: CXX=g++-4.9
      before_install:
        - brew update
        - brew install valgrind
        - HOMEBREW_CC=gcc-4.9 HOMEBREW_CXX=g++-4.9 brew install --build-from-source cppunit
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      before_install:
        - brew update
        - brew install valgrind cppunit
before_script: mkdir build && cd build
script: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGEOMETRY_BUILD_TESTS=ON -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -pedantic" .. && make && ctest --verbose -D ExperimentalMemCheck
